function skillsMember() {
    const skills = [
        'HTML',
        'CSS',
        'JavaScript',
        'React',
        'Node.js',
        'Express.js',
        'MongoDB',
        'Mongoose',
        'GraphQL',
        'Apollo',
        'REST API',
        'Git',
        'GitHub',
        'Heroku',
        'Netlify',
        'Vercel',
        'Python',
        'Django',
        'Flask',
        'C',
        'C++',
        'Java',
        'R',
        'SQL',
        'PHP',
        'Laravel',
        'CodeIgniter',
        'Vue.js',
        'Nuxt.js',
        'Next.js',
        'Svelte',
        'Angular',
        'Redux',
        'MobX',
        'Webpack',
        'Gulp',
        'Grunt',
        'Jest',
        'Mocha',
        'Chai',
        'Cypress',
        'Puppeteer',
        'Jasmine',
        'Karma',
        'Selenium',
        'Jenkins',
        'Travis CI',
        'Circle CI',
        'Docker',
        'Kubernetes',
        'AWS',
        'Azure',
        'Google Cloud',
        'Firebase',
        'Netlify',
    ];

    return skills;
}